- name: Create Docker context for Grafana
  become: true
  shell: docker context create {{item.name}} --docker "host=ssh://root@{{item.ip}}"
  ignore_errors: true
  tags: 
    - local
  loop: 
    - {name: 'Grafana1', ip: '178.128.101.240'} 
    - {name: 'Grafana2', ip: '178.128.109.226'}

- name: Deploy Grafana on Grafana nodes
  become: true
  shell: docker context use {{item.name}} | docker-compose up -f {{item.file_path}} -d
  ignore_errors: true
  tags: 
    - local
  loop:
    - {name: 'Grafana1', file_path = '/home/haivm/Documents/Viettel-Digital-Talent-Program-2022/Practice-4/Tran-Quang-Hai/ha/docker-compose.yml'}
    - {name: 'Grafana2', file_path = '/home/haivm/Documents/Viettel-Digital-Talent-Program-2022/Practice-4/Tran-Quang-Hai/ha/docker-compose.yml'}