version: '3.0'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27016:27017
  pythonapp:
    build: python-http/
    ports:
      - 5009:5000
  nginx:
    build: nginx/
    restart: always
    ports:
      - 5005:80
    depends_on:
      - pythonapp